version: '3'

services: 
  pg:
    image: postgres
    restart: always
    container_name: database_point
    ports: 
      - "9000:5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pointDaLarica